apiVersion: v1
kind: Service
metadata:
  name: dynamic-service
  namespace: pythontest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: dynamic-deployment
  type: ClusterIP
