apiVersion: v1
kind: Service
metadata:
  annotations:
    yandex.cloud/load-balancer-type: "Internal"
    yandex.cloud/subnet-id: "e9blqiokfqs7tt0imu2o" #FILL IN YOUR SUBNET ID
  name: static-service
  namespace: pythontest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static-deployment
  type: ClusterIP
