---
apiVersion: v1
kind: Namespace
metadata:
  name: pythontest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  namespace: pythontest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-deployment
  template:
    metadata:
      namespace: pythontest
      labels:
        app: static-deployment
    spec:
      containers:
        - name: static-deployment
          image: docker.io/tmarkunin/static_site:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
