kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
namespace: secondary
name: deny-from-other-namespaces
spec:
podSelector:
matchLabels:
ingress:
- from:
- podSelector: {}

-apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: the-project
  name: deployer
rules:
- apiGroups: ["*"]
  resources: ["deployments","configmaps", "services", "persistentvolumeclaims","pods","secrets","ingresses", “networkpolicies”]
  verbs: ["create","get","delete","list","update","edit","watch","exec","patch"]

